package log_request_type

const (
	REQUEST_BUSINESS_TYPE_INSERT = 1 // 新增
	REQUEST_BUSINESS_TYPE_UPDATE = 2 // 修改
	REQUEST_BUSINESS_TYPE_DELETE = 3 // 删除
	REQUEST_BUSINESS_TYPE_GRANT  = 4 // 授权
	REQUEST_BUSINESS_TYPE_EXPORT = 5 // 导出
	REQUEST_BUSINESS_TYPE_IMPORT = 6 // 导入
	REQUEST_BUSINESS_TYPE_FORCE  = 7 // 强退
	REQUEST_BUSINESS_TYPE_GENCOD = 8 // 生成代码
	REQUEST_BUSINESS_TYPE_CLEAN  = 9 // 清空数据
)
